tengined:
  daemon: true
  load_path: "/var/lib/tengine"
  pid_dir: "/var/run/tengined_pids"
  status_dir: "/var/run/tengined_status"
  activation_dir: "/var/run/tengined_activations"
  heartbeat_period: 600
  confirmation_threshold: "warn"
event_queue:
  queue:
    name: tengine_event_queue2
